name: Elixir Tests
on:
  push:
  pull_request:
jobs:
   mix-test:
      runs-on: ubuntu-22.04
      steps:
         - name: Checkout repository
           uses: actions/checkout@v7

         - name: Setup Elixir
           uses: erlef/setup-beam@v1
           with:
              elixir-version: 1.18.3
              otp-version: OTP-26.0
         - name: Setup node
           uses: actions/setup-node@v7

         - name: Install puppeteer-img
           run: npm install -g @algora/puppeteer-img

         - name: Setup Chrome
           run: npx puppeteer browsers install chrome

         - name: Setup Imagemagick
           run: sudo apt-get install imagemagick

         - name: Run setup
           run: mix setup

         - name: Start Phoenix server
           run: |
            mix phx.server &
            sleep 5
            curl http://localhost:4002  # Verify server is running

         - name: Run tests
           run: mix test --include start
           env:
             MIX_ENV: test
